### ISSUE TITLE
Fix errors in Recess

### ISSUE THREAD

**Issue by karlhorky** [dflock/SublimeLinter-recess#3]
In order to fix #1, the errors in Recess need to be addressed. Maybe through a pull request to Recess or through using one of the forks available we can get these done.

- [ ] Recess returns output in a different format if there's a CSS/LESS syntax error (ignoring the `--format` parameter)
- [ ] Fix line number offsets. Currently Recess returns the line number in the final compiled css file, not the less file.

@dflock Does this look like a complete list?

**Comment by karlhorky** [comment]
There is [a v2.0.0 branch](https://github.com/twitter/recess/tree/v2.0.0) of Recess which may be interesting. Doesn't seem to work for me when cloning it locally, but maybe I'm missing something. [I've asked](https://twitter.com/karlhorky/status/552457851042824192) the maintainer for a status update on this.

**Comment by dflock** [comment]
This sounds like a complete list - but I don't think the second one is fixable at the moment in recess. It doesn't actually lint the less file itself - it compiles it to .css and the runs an existing css-linter over that. I think the only way to do that currently is to use `lessc --lint`.

It would probably be better to just build a SublimeLinter plugin that uses `lessc --lint` as it's linter - however it's a bit basic and only reports glaring syntax errors, not warnings or hints for things to improve.

**Comment by karlhorky** [comment]
Closing since Recess is no longer maintained.
